### ISSUE TITLE
Throwing.BiConsumer

### ISSUE THREAD

**Issue by NikolayMetchev** [diffplug/durian#4]
Just came across your Errors library.
You probably need a java.util.function.BiConsumer equivalent in Throwing (for use in Errors).
Just a suggestion.

**Comment by panga** [comment]
Same issue for BiFunction

**Comment by nedtwigg** [comment]
These have both been present in `Throwing` since at least 2016.  https://diffplug.github.io/durian/javadoc/3.4.0/
