### ISSUE TITLE
Cannot find annotation method 'justification()' in type 'SuppressFBWarnings'

### ISSUE THREAD

**Issue by andrewparmet** [diffplug/durian#5]
I'm getting these warnings when building.  [I've read](https://issues.apache.org/jira/browse/DIRAPI-252) that they may be caused by accidentally importing `edu.umd.cs.findbugs.annotations.SuppressFBWarnings` instead of `java.lang.SuppressWarnings` as you do [here](https://github.com/diffplug/durian/blob/10631a3480e5491eb6eb6ee06e752d8596914232/src/com/diffplug/common/base/Comparison.java#L20) and [here](https://github.com/diffplug/durian/blob/10631a3480e5491eb6eb6ee06e752d8596914232/src/com/diffplug/common/base/Suppliers.java#L25).  Is this intentional?

**Comment by nedtwigg** [comment]
Yep, I used SuppressFBWarnings intentionally.  You can fix the warnings by adding the findbugs warnings as a compileOnly dependency.

**Comment by andrewparmet** [comment]
Whoops - I see I confused SupressWarnings as SupressFBWarnings in java.lang.  I understand that a compileOnly warning isn't a runtime dependency, but it is a dependency when warning-free compilation is require by a build process.  Doesn't this defeat the dependency-free goal stated in the README?

**Comment by nedtwigg** [comment]
I find FindBugs invaluable during development.  I agree that the compileOnly issue is a minor but real violation of the dependency-free goal.  I'd love to merge a PR that strips out the annotations as part of the deployment process :)

**Comment by andrewparmet** [comment]
I didn't know such a thing was possible. After a brief search I don't see anything easily workable, so I'll just let sleeping dogs lie - unless you know more about this than I do and can recommend a way forward.

**Comment by nedtwigg** [comment]
I don't know any easy ways.  Proguard *might* be able to do it, and certainly you could do it with a bytecode manipulation tool such as ASM.  Every library that uses an annotation-based checker is going to have this problem, so it might be worth building a gradle plugin because we're not the only lib with this issue.
