### ISSUE TITLE
Errors doesn't work with BiFunction

### ISSUE THREAD

**Issue by itsravi77** [diffplug/durian#7]
I have a bifunction and BiConsumer something like this:

private void transformAndSave(Path path, String outputDir) throws IOException{
}

Which I wanted to use as lambda, found your library on StackOverflow, but when I tried using it, I realized that it doesn't support BiFunctions/BiConsumer, only Function/Consumer is supported.

Are you planning to add the support for the same?

**Comment by nedtwigg** [comment]
Support is not planned.  I would recommend

```java
BiConsumer<Path, String> wrapped = (path, outputDir) -> Errors.rethrow().get(() -> transformAndSave(path, outputDir));
// or
private void transformAndSaveRethrow(Path path, String outputDir) {
  try {
    transformAndSave(path, outputDir)
  } catch (Exception e) {
    throw Errors.asRuntime(e);
  }
}
```

See:

https://github.com/diffplug/durian/blob/10631a3480e5491eb6eb6ee06e752d8596914232/test/com/diffplug/common/base/ErrorsExample.java#L194-L197
