### ISSUE TITLE
Consider publishing separately Errors and Throwing

### ISSUE THREAD

**Issue by oliviercailloux** [diffplug/durian#8]
I like very much the error wrapping functionality provided by Durian. But I refrain from including Durian in my project because it duplicates some classes from Guava, which I find inelegant. (I also use Guava as a dependency anyway.)

Please consider publishing separately just the `Errors` and `Throwing` classes. 

With a bit of luck, the resulting library could become the de-facto standard for throwing versions of the classical functional interfaces. Which would be very nice, avoiding every project having its own version of a `ThrowingFunction`.

**Comment by nedtwigg** [comment]
Thanks for this suggestion!  I had hoped an adoption of this sort would happen too, and it has become a somewhat popular transitive dependency.  Given that Java 8 is now quite old, and people have already faced this problem for a long time, I think it's difficult to change the popularity trajectory of durian at this stage.  I really value stability in the projects that I consume, and I try to do the same in projects that I publish.

The good news is that, thanks to how java handles functional interfaces, it's very easy to convert between different `Throwing` implementations, even if each library copy-pastes the code into their implementation, e.g.

```javs
a.Throwing.Runnable r = () -> {something();};
b.Throwing.Runnable other = r::run;
```

It's not ideal, but if the duplicated classes bother you, you can just copy-paste them into your own artifact as shown.  Another option is to use your IDE's type filtering.  I don't know how IntelliJ does it, but in eclipse you can [filter out unwanted imports like this](http://blog.vogella.com/2009/04/01/eclipse-organize-imports-filter/).

I appreciate and hear your suggestion, but I value stability too highly to take it onboard.

**Comment by oliviercailloux** [comment]
Publishing separately without changing the content of the classes would not be a breaking change, I’d say. You could have durian depend on the new part. Or you could keep durian as a whole by making it a uber-jar that would include the sub-library. Consumers would see no difference. The new publication would be considered a new project.

I am not sure I understand all of your suggestions, but it seems to me they are all not a very elegant way of achieving a standard throwing version of the classical functional interfaces. (Yes, I know, and sometimes use, Eclipse’s filtering ability, but here it feels like working around a problem that should have been avoided by not including duplicated classes in the first place.)

**Comment by oliviercailloux** [comment]
Thinking again about this (and still regretting very much that one can’t simply re-use the `Throwing` and `Errors` part of durian without also having duplicated Guava classes in one’s project), I still wonder if my suggestion has been well understood.

Don’t you agree that publishing separately `Throwing` and `Errors`, and making Durian depend on the new library, would not be a breaking change?

Sorry to insist, if unappropriate. But I want to make sure the current unfortunate state of fact is not simply the result of a misunderstanding.

**Comment by nedtwigg** [comment]
Not inappropriate, I appreciate you reaching out :)

Module systems in general, and especially JPMS, don't like it if you split packages.  So either `Throwing` and `Errors` move to a new package, or all the rest of it does.  It's not a huge breaking change, but it is nonetheless definitely a breaking change.

That said, I have been reconsidering a restructuring of this project.  Guava has finally come along for the Java 8 ride, so much of Durian is no longer necessary, and perhaps it makes sense to focus on this aspect.  It's good to know that there is interest, I'll think on this.
