### ISSUE TITLE
No builds included

### ISSUE THREAD

**Issue by Monniasza** [diffplug/durian#9]
This library doesn't contain any Durian builds, but contains Gradle wrapper.

**Comment by nedtwigg** [comment]
I don't understand.  Can you elaborate?

**Comment by Monniasza** [comment]
This release doesn't include compiled JAR files.

**Comment by nedtwigg** [comment]
The jars are available on mavenCentral: https://search.maven.org/search?q=g:com.diffplug.durian%20AND%20a:durian&core=gav
